version: '3.7'
services:
  postgres_db:
    image: postgres
    container_name: retro-football-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=retro-football
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
      - ./data/sql:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=ADMIN12345
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.dev
    container_name: retro-football-api
    ports:
      - "3080:3080"
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - postgres_db
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: retro-football-client
    environment:
      - CHOKIDAR_USEPOLLING=true 
    volumes:
      - './client:/app'
      - '/app/node_modules'
    depends_on:
      - api
    ports:
      - "3000:3000"
  
volumes:
  db-data:
  pgadmin: